name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Copy config file
        run: cp app/src/config.template.js app/src/config.js

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-22.04
    needs: test

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      # QEMU (multi-arch support)
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4
        with:
          platforms: all

      # Buildx builder
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build & push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            mirotalk/sfu:latest
            mirotalk/sfu:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
